### ISSUE TITLE
Exercise: Simple CPU Design in SystemVerilog Using MAFIA TFM

### ISSUE THREAD

**Issue by amichai-bd** [FPGA-MAFIA/fpga_mafia#553]
# Target
- Become familiar with HW RTL design with CPU design orientation by designing a simple CPU in SystemVerilog.

# Background
- The MAFIA Project is a HW/SW co-design platform for the development of embedded systems.
- To develop a HW/SW co-design platform, we need to understand the HW design and SW design.
- The MAFIA project has developed an ecosystem for the HW/SW project development.
- Upon completion, you'll be equipped to contribute to the MAFIA project with your knowledge in HW, SW, and tools, flows, and methodology (TFM).

# Task
### HW Development - initial sub-modules
- [x] Understand the basic CPU architecture. (Fetch, Decode, Execute, Memory-Access, WriteBack)
- [x] Learn the proprietary ISA (Instruction Set Architecture) for this exercise CPU design.
- [x] Understand the basic SystemVerilog design - Coding style, Data path and Control path, cycle alignment, and pipeline.
- [x] Create a new source/exercise & verif/exercise folder in the MAFIA root directory.
- [x] Start designing sub-modules of the CPU & simple simulation, verification & testing
    - Use other MAFIA design for reference on the directory structure and coding style.
    - Example for sub unit build command: ``` ./build.py -dut exercise -top alu_tb -hw -sim```
    - Note there is no "app" option for the sub-module build command.
    - [x] ALU (Arithmetic Logic Unit) Design & TB (Test Bench)
    - [x] Register File Design & TB (Test Bench)
    - [x] Decoder Design & TB (Test Bench)

### SW Development
- [x] Understand the instruction and data memory spaces - make sure to use the correct memory space in your assembly code
- [x] Design a simple R-Type assembly test (No Hazard, No Forwarding, No Branch) 
    - Run it using the MAFIA tools and verify GCC results.
    - Use the command ```./build.py -dut exercise -test r_type_alive -app```

### HW Development - integrate the sub-modules
- [x] Create the CPU top module exercise.sv and integrate the sub-modules into it
    - Add more sub-modules as needed (fetch, memory access, write back, etc.)
    - Use the common sub-module for I_MEM and D_MEM memory instantiation
    - The CPU is a 3 stage pipeline - use the correct signal names suffixes for each stage
        - Fetch
        - Decode, Execute, Memory-Access
        - WriteBack
    - Make sure to use correct pipeline stages and control signals
- [x] Test the integrated CPU with the R-Type assembly test:
    - Use the command ```./build.py -dut exercise -test r_type_alive -app -hw -sim```
    - Note: the default -top is the "exercise_tb" which matches -dut "exercise"

### Enhance the debug and verification environment
- [x] Create trackers as log files for the:
    - fetch             - time, PC, instruction
    - ALU               - time, PC, instruction, ALU operation, ALU input_1, ALU input_2, ALU output
    - Memory access     - time, PC, RD/WR, address, data
    - Write back        - time, PC, Register destination, data

### regression test    
- [ ] Write a level0 regression test for the CPU design which you will update as you add more features.
    - Use the command ```./build.py -dut exercise -regress level0 -app -hw -sim```

### Testing more features
- [x] Design a simple I-Type & R-Type assembly test (No Hazard, No Forwarding, No Branch) 
    - Use the command ```./build.py -dut exercise -test i_type_alive -app -hw -sim```
- [x] Design a simple Load/Store assembly test (No Hazard, No Forwarding, No Branch)
    - Use the command ```./build.py -dut exercise -test load_store_alive -app -hw -sim```
- [x] Design a simple data hazard assembly test (support forwarding, No Branch)
    - Use the command ```./build.py -dut exercise -test data_hazard_alive -app -hw -sim```
- [x] Design a simple Load Hazard assembly test (support forwarding, No Branch)
    - Use the command ```./build.py -dut exercise -test load_hazard_alive -app -hw -sim```
- [ ] Design a simple Jump assembly test
    - Use the command ```./build.py -dut exercise -test jump_alive -app -hw -sim```
- [ ] Design a simple Branch assembly test
    - Use the command ```./build.py -dut exercise -test branch_alive -app -hw -sim```

### Final regression test
- [ ] design a test that includes all ISA of this exercise CPU design
    - Try to have a verifiable test that has a testable result (e.g. a final memory section value of a bubble sort or similar)

# The ISA (Instruction Set Architecture) for this exercise CPU design
NOTE: The ISA is a subset of the RISC-V ISA. use the RISC-V ISA manual for reference.
### R-Type Instructions:
- ADD: 
- SUB:
- AND:
- OR:
- XOR:
- SLL:  - Shift Left Logical
- SRL:  - Shift Right Logical
- SRA:  - Shift Right Arithmetic
- SLT:  - Set Less Than
- SLTU: - Set Less Than Unsigned

### I-Type Instructions:
- ADDI:
- ANDI:
- ORI:
- XORI:
- SLLI: - Shift Left Logical Immediate
- SRLI: - Shift Right Logical Immediate
- SRAI: - Shift Right Arithmetic Immediate
- SLTI: - Set Less Than Immediate
- SLTIU:- Set Less Than Immediate Unsigned

### Load/Store Instructions:
- LW:  - Load Word
- SW:  - Store Word

### Control Transfer Instructions:
- J:   - Jump
- BEQ: - Branch if Equal

**Comment by NoamRahat** [comment]
Hi @amichai-bd, I will suspend this task untill 10.4 due to exam period

**Comment by NoamRahat** [comment]
Hi @amichai-bd,
I have craeted a new branch for this task called "nr_cpu_ex_#553". I will commit there my progress so you can track my work.
Right niw I'm focusing on "Understand the basic SystemVerilog design - Coding style, Data path and Control path, cycle alignment, and pipeline."

**Comment by amichai-bd** [comment]
@NoamRahat please let me and Roman know if you have any questions!

**Comment by NoamRahat** [comment]
Sure

**Comment by NoamRahat** [comment]
Hi @amichai-bd ,
I have started playing with thw SV, thinking starting with the ALU will be the easiest.
@roman012285 helped me with reminding the hierarchy of the project, using the .f file and more and time out bug detection.
my commits are posted here, so you can take a look.
I saw in our mini_core_rrv implemntation there is a input for the imm values.
if I want to use a mux for selecting src2 / imm how can I do that?

**Comment by amichai-bd** [comment]
@NoamRahat - Great progress!
Couple of notes: 
this cant be the same SLT vs SLTU (sign and unsigned operation)
![image](https://github.com/FPGA-MAFIA/fpga_mafia/assets/81047407/05052ba8-f6cd-4885-a83a-89debe2ac271)

I think you could remove this file:
![image](https://github.com/FPGA-MAFIA/fpga_mafia/assets/81047407/562b9b8f-22e9-49af-a626-2aa3d6eb0c8c)

I will note that seems like you are getting the hand of it..
Feel free to look at the big_core or mini_core logic to get inspiration.
Make sure to create your own TB for each module you create.

Please post here any questions you may have.

**Comment by NoamRahat** [comment]
Hey @amichai-bd ,
https://github.com/FPGA-MAFIA/fpga_mafia/commit/e1e6093747dc747f3b863231c4c49fadea640355

I would like to have a session about implemnting cocept of cycles + pipline and crtl signals.
I have an exam on Thersday (9.5) + I'm back to work, so don't know if it's a good idiea to do that next week.
However from the week after I promise to give a serious boost.

**Comment by NoamRahat** [comment]
Hi @amichai-bd , I have added the RF sub-module & TB: https://github.com/FPGA-MAFIA/fpga_mafia/commit/c06c0ba8e58f046605e253f0a05eb38499e30ca1
I would like to give review and feedback.
Thanks

**Comment by NoamRahat** [comment]
Hi @amichai-bd , I think a have done enough progress so we can schedule a meeting to complete this task and countiue starting with project.
please look a the 2 last commits:
https://github.com/FPGA-MAFIA/fpga_mafia/commit/cf46dcfb9fecc046b6cd5825dd0df64e3fe10474
https://github.com/FPGA-MAFIA/fpga_mafia/commit/cdec7b4b481481a49dfa88ccf71f163c97af42e9

**Comment by NoamRahat** [comment]
Hi @amichai-bd , Shavua Tov!
I have created a simple assembly test, seems it runs ok:
https://github.com/FPGA-MAFIA/fpga_mafia/commit/0c9114da7384362b4d108c9fd8e035c14acc4f6b
I think we can have a meeting to copmlete whats left in this task, close this isuue, and continue foward.

**Comment by amichai-bd** [comment]
I agree.
Lest schedule this week via watsapp

**Comment by amichai-bd** [comment]
- Create a tracker for the reg write (PC, RegDst,RegData - log only if RegWrEn)
- create a test that has a data hazard - send screenshot of data "corruption" (tracker + elf)
- Solve the Data Hazard - send sscreen shot of the "correct" reg write (tracker + elf + RTL fix)

**Comment by NoamRahat** [comment]
Hi @amichai-bd ,
I and @jacobavitan837 have worked today with support from @roman012285 on adding tracking functionality to ex_core 
- Updated ex_core_tb.sv to include a tracker for logging register file and ALU activities.
- Created a new tracker file `ex_core_trk.vh` to monitor and log specific signals during simulation:
  - Log register file activities when RegWrEn is enabled.
  - Log ALU operations on each clock cycle.
- Modified `ex_core_verif_list.f` to include the directory of the new tracker file.
- Ensured that the appropriate hierarchy paths are used to access internal signals of the `ex_core` module.
- Added logging to:
  - `reg_file.log`: Logs PC, RegDst, and RegWrData when RegWrEn is enabled.
  - `alu_file.log`: Logs PC, AluIn1, AluIn2, and AluOut on each positive clock edge.
  all described is commited in: https://github.com/FPGA-MAFIA/fpga_mafia/commit/0c4f1f2041162e80276e6ec778dc5078a2fbf64f
  
###NTBD:
####Create trackers as log files for the:
- fetch - time, PC, instruction
- ALU - time, PC, instruction, ALU operation, ALU input_1, ALU input_2, ALU output
- Memory access - time, PC, RD/WR, address, data
- Write back - time, PC, Register destination, data
- Create a test that has a data hazard - send screenshot of data "corruption" (tracker + elf)
- Solve the Data Hazard - send sscreen shot of the "correct" reg write (tracker + elf + RTL fix)
Please god will do that tommorow.

**Comment by NoamRahat** [comment]
> * Create a tracker for the reg write (PC, RegDst,RegData - log only if RegWrEn)
> * create a test that has a data hazard - send screenshot of data "corruption" (tracker + elf)

#### Example of Data Hazard:
##### Screenshot of data "corruption" (tracker + elf):
![image](https://github.com/FPGA-MAFIA/fpga_mafia/assets/96725773/71855468-8ff1-4f09-af85-7a2ae74ca32e)
in this figure we can see that a **data hazard** caused by a **Read After Write (RAW)** dependency @ address `0x38`.
![image](https://github.com/FPGA-MAFIA/fpga_mafia/assets/96725773/1d587602-facd-452a-b65a-b773b976b71e)
```assembly
  34:	001103b3          	add	x7,x2,x1    ; x7 = x2 + x1 (x7 = 2 + 1 = 3)
  38:	40238433          	sub	x8,x7,x2    ; x8 = x7 - x2 (x8 = 3 - 2 = 1)
```
- **Instruction at `0x34` (add x7, x2, x1)**: This instruction adds the contents of registers `x2` and `x1` (`x2 = 2` and `x1 = 1`).
- **Instruction at `0x38` (sub x8, x7, x2)**: This instruction subtracts the contents of `x2` from `x7` (`x7 = 3`).

### Hazard Analysis:
- **Data Hazard (@ `0x38`)**:
  - **RAW (Read After Write)**: The instruction at `0x38` (`sub x8, x7, x2`) reads the value of `x2` immediately after it was updated by the instruction at `0x34` (`add x7, x2, x1`).
  - **Affected Instruction**: The `SUB` instruction at PC = 38 (`sub x8,x7,x2`).
  - **Expected Value**: After `ADD` at PC = 34 (`add x7,x2,x1`), `x7` should be `3` (`x2 + x1`).
  - **Actual Value**: `SUB` at PC = 38 reads `x7` too early, still `0` (initial value), not `3`.
  - **Reason for Mismatch**: In a pipelined CPU, `SUB` fetches `x7` before `ADD` updates it to `3`.
  - **Impact**: `SUB` subtracts `x2` from `x7` (`0` instead of `3`), giving incorrect `x8=fffffffe (-2)` value.
  - **Corruption**: `x8` gets wrong value due to `SUB` using outdated `x7`.

**Comment by amichai-bd** [comment]
Great analasys!

Now solve with forwoding unit!

**Comment by NoamRahat** [comment]
> Great analasys!
> 
> Now solve with forwoding unit!
Hi @amichai-bd 
this is my solution:
1. **ForwardedRegRdData1Q101H** and **ForwardedRegRdData2Q101H**:
    - These signals determine whether to use the forwarded data (from the previous instruction) or the data read from the register file.

    ```verilog
    assign ForwardedRegRdData1Q101H = (CtrlRfQ101H.RegSrc1 == RegDstQ102H && RegWrEnQ102H) ? RegWrDataQ102H : RegRdData1Q101H;
    assign ForwardedRegRdData2Q101H = (CtrlRfQ101H.RegSrc2 == RegDstQ102H && RegWrEnQ102H) ? RegWrDataQ102H : RegRdData2Q101H;
    ```

    - **Condition**: Checks if the source register of the current instruction (`RegSrc1` or `RegSrc2`) matches the destination register of the previous instruction (`RegDstQ102H`) and if the write enable signal (`RegWrEnQ102H`) is asserted.
    - **Action**: If the condition is true, it forwards the data from the previous instruction (`RegWrDataQ102H`). Otherwise, it uses the data read from the register file (`RegRdData1Q101H` or `RegRdData2Q101H`).

2. **ALU Inputs**:
    - The ALU inputs are assigned using the forwarded data.

    ```verilog
    assign AluIn1Q101H = ForwardedRegRdData1Q101H;
    assign AluIn2Q101H = (opcodeQ101H == I_OP) ? immQ101H : ForwardedRegRdData2Q101H;
    ```

    - **AluIn1Q101H**: Always takes the value of `ForwardedRegRdData1Q101H`.
    - **AluIn2Q101H**: Takes the immediate value (`immQ101H`) if the current instruction is an immediate operation (`I_OP`); otherwise, it takes the value of `ForwardedRegRdData2Q101H`.


![image](https://github.com/FPGA-MAFIA/fpga_mafia/assets/96725773/c9c0867f-b336-4f59-93f2-b22b5241ad97)
here we can see the issue is fixed and the instruction @ 0x38 (sub x8, x7, x2) reads the **correct** value of x7 immediately after it was updated by the instruction @ 0x34 (add x7, x2, x1).

**Comment by amichai-bd** [comment]
Great job!

I see a bug in your forwarding unit.

Please produce the bug - then solve it.

Addi x0, x0, 1
Add x5, x0, x0

**Comment by NoamRahat** [comment]
> Great job!
> 
> I see a bug in your forwarding unit.
> 
> Please produce the bug - then solve it.
> 
> Addi x0, x0, 1 Add x5, x0, x0

https://github.com/FPGA-MAFIA/fpga_mafia/commit/ee76ba84bc6ce202001169de34ef326b4cb5fa49
[[](https://github.com/FPGA-MAFIA/fpga_mafia/commit/ee76ba84bc6ce202001169de34ef326b4cb5fa49)https://github.com/FPGA-MAFIA/fpga_mafia/issues/553[]: Fix: forwarding condition does not handle the zero register c…](https://github.com/FPGA-MAFIA/fpga_mafia/commit/ee76ba84bc6ce202001169de34ef326b4cb5fa49) …
[ee76ba8](https://github.com/FPGA-MAFIA/fpga_mafia/commit/ee76ba84bc6ce202001169de34ef326b4cb5fa49)
…orrectly. Forwarding from or to x0 should not happen as x0 is always zero.

Bug Fix:
Modified the forwarding logic to ensure that no forwarding occurs when the source or destination register is x0.
**Explanation:**

1. **Condition Update:**
   - Added `CtrlRfQ101H.RegSrc1 != 5'b00000` and `CtrlRfQ101H.RegSrc2 != 5'b00000` to ensure that forwarding does not occur when the source register is x0.
2. **Behavior:**
   - If the source register is not x0, and it matches the destination register of the previous instruction with the write enable signal asserted, it forwards the data.
   - Otherwise, it uses the data read from the register file.
